// <auto-generated />
using CoachHussien.Application.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoachHussien.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251122122408_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoachHussien.Domain.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Carbs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 35m,
                            Carbs = 5.2m,
                            CategoryId = 1,
                            Fat = 0.1m,
                            Name = "لبن خالي الدسم (لامار)",
                            Protein = 3.3m
                        },
                        new
                        {
                            Id = 2,
                            Calories = 42m,
                            Carbs = 3.8m,
                            CategoryId = 1,
                            Fat = 1.5m,
                            Name = "لبن صويا",
                            Protein = 2.5m
                        },
                        new
                        {
                            Id = 3,
                            Calories = 50m,
                            Carbs = 3.61m,
                            CategoryId = 1,
                            Fat = 0.2m,
                            Name = "زبادي يوناني ساده (جهينة)",
                            Protein = 8.33m
                        },
                        new
                        {
                            Id = 4,
                            Calories = 51m,
                            Carbs = 5m,
                            CategoryId = 1,
                            Fat = 1.5m,
                            Name = "زبادي لايت (جهينة)",
                            Protein = 3.4m
                        },
                        new
                        {
                            Id = 5,
                            Calories = 57m,
                            Carbs = 4.5m,
                            CategoryId = 1,
                            Fat = 3m,
                            Name = "لبن خالي من اللاكتوز (جهينة)",
                            Protein = 3m
                        },
                        new
                        {
                            Id = 6,
                            Calories = 63m,
                            Carbs = 5m,
                            CategoryId = 1,
                            Fat = 3.4m,
                            Name = "لبن كامل الدسم",
                            Protein = 3.2m
                        },
                        new
                        {
                            Id = 7,
                            Calories = 82m,
                            Carbs = 2.9m,
                            CategoryId = 1,
                            Fat = 9.2m,
                            Name = "توفو",
                            Protein = 3.6m
                        },
                        new
                        {
                            Id = 8,
                            Calories = 91m,
                            Carbs = 2.8m,
                            CategoryId = 1,
                            Fat = 3.5m,
                            Name = "جبنة قريش",
                            Protein = 12m
                        },
                        new
                        {
                            Id = 9,
                            Calories = 99m,
                            Carbs = 0.2m,
                            CategoryId = 1,
                            Fat = 0.3m,
                            Name = "جمبري",
                            Protein = 24m
                        },
                        new
                        {
                            Id = 10,
                            Calories = 100m,
                            Carbs = 10m,
                            CategoryId = 1,
                            Fat = 10m,
                            Name = "شرائح دجاج (أطياب)",
                            Protein = 15m
                        },
                        new
                        {
                            Id = 11,
                            Calories = 102.7m,
                            Carbs = 0.3m,
                            CategoryId = 1,
                            Fat = 19m,
                            Name = "بسطرمة",
                            Protein = 2.8m
                        },
                        new
                        {
                            Id = 12,
                            Calories = 103m,
                            Carbs = 1m,
                            CategoryId = 1,
                            Fat = 0m,
                            Name = "تونة لايت (صن شاين)",
                            Protein = 23m
                        },
                        new
                        {
                            Id = 13,
                            Calories = 106m,
                            Carbs = 6m,
                            CategoryId = 1,
                            Fat = 0m,
                            Name = "بييكون (مخلي من الدهون)",
                            Protein = 18m
                        },
                        new
                        {
                            Id = 14,
                            Calories = 116m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 0.8m,
                            Name = "تونة لايت (فيشر مان)",
                            Protein = 25.5m
                        },
                        new
                        {
                            Id = 15,
                            Calories = 118m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 1.3m,
                            Name = "سمك هامور (بعد الطهي)",
                            Protein = 24.8m
                        },
                        new
                        {
                            Id = 16,
                            Calories = 124m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 2.6m,
                            Name = "سمك قاروص (بعد الطهي)",
                            Protein = 23.6m
                        },
                        new
                        {
                            Id = 17,
                            Calories = 128m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 2.6m,
                            Name = "سمك بلطي (بعد الطهي)",
                            Protein = 26.2m
                        },
                        new
                        {
                            Id = 18,
                            Calories = 131m,
                            Carbs = 5m,
                            CategoryId = 1,
                            Fat = 7m,
                            Name = "جبنة فيتا لايت (بريزيدون)",
                            Protein = 12m
                        },
                        new
                        {
                            Id = 19,
                            Calories = 135m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 3.5m,
                            Name = "سمك دنيس (بعد الطهي)",
                            Protein = 24.2m
                        },
                        new
                        {
                            Id = 20,
                            Calories = 138m,
                            Carbs = 14m,
                            CategoryId = 1,
                            Fat = 1m,
                            Name = "قطع سيتان نباتي (Not Fried)",
                            Protein = 19m
                        },
                        new
                        {
                            Id = 21,
                            Calories = 140m,
                            Carbs = 5m,
                            CategoryId = 1,
                            Fat = 8m,
                            Name = "جبنة لايت اسبريد (بريزيدون)",
                            Protein = 12m
                        },
                        new
                        {
                            Id = 22,
                            Calories = 141m,
                            Carbs = 6.8m,
                            CategoryId = 1,
                            Fat = 6.7m,
                            Name = "سلطة تونة مكسيكية (فيشر مان)",
                            Protein = 11.4m
                        },
                        new
                        {
                            Id = 23,
                            Calories = 149m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 4.4m,
                            Name = "سلمون",
                            Protein = 25.6m
                        },
                        new
                        {
                            Id = 24,
                            Calories = 149m,
                            Carbs = 13m,
                            CategoryId = 1,
                            Fat = 1m,
                            Name = "شرائح دجاج نباتي (Not Fried)",
                            Protein = 20m
                        },
                        new
                        {
                            Id = 25,
                            Calories = 150m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 4.9m,
                            Name = "سمك بوري (بعد الطهي)",
                            Protein = 24.8m
                        },
                        new
                        {
                            Id = 26,
                            Calories = 153m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 4.5m,
                            Name = "لحمة مفرومة (متشفية من غير دهون)",
                            Protein = 26.4m
                        },
                        new
                        {
                            Id = 27,
                            Calories = 153m,
                            Carbs = 4.3m,
                            CategoryId = 1,
                            Fat = 12m,
                            Name = "جبنة فلاديفيا لايت",
                            Protein = 6m
                        },
                        new
                        {
                            Id = 28,
                            Calories = 160m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 4.5m,
                            Name = "ستيك لحمة",
                            Protein = 29.9m
                        },
                        new
                        {
                            Id = 29,
                            Calories = 165m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 3.6m,
                            Name = "صدور دجاج (بعد الطهي)",
                            Protein = 31m
                        },
                        new
                        {
                            Id = 30,
                            Calories = 167m,
                            Carbs = 0.7m,
                            CategoryId = 1,
                            Fat = 6.5m,
                            Name = "كبدة دجاج (بعد الطهي)",
                            Protein = 24.5m
                        },
                        new
                        {
                            Id = 31,
                            Calories = 170m,
                            Carbs = 2m,
                            CategoryId = 1,
                            Fat = 5m,
                            Name = "فصوص تركي",
                            Protein = 29.29m
                        },
                        new
                        {
                            Id = 32,
                            Calories = 170m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 6m,
                            Name = "روست بيف",
                            Protein = 29m
                        },
                        new
                        {
                            Id = 33,
                            Calories = 187m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 6.63m,
                            Name = "مكعبات لحمة حمراء (بعد الطهي)",
                            Protein = 29.81m
                        },
                        new
                        {
                            Id = 34,
                            Calories = 191m,
                            Carbs = 5.1m,
                            CategoryId = 1,
                            Fat = 5.3m,
                            Name = "كبدة بقري (بعد الطهي)",
                            Protein = 29.1m
                        },
                        new
                        {
                            Id = 35,
                            Calories = 195m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 10.4m,
                            Name = "سردين",
                            Protein = 25.3m
                        },
                        new
                        {
                            Id = 36,
                            Calories = 211m,
                            Carbs = 14.68m,
                            CategoryId = 1,
                            Fat = 13.26m,
                            Name = "كرات لحم نباتي (Las Vegan)",
                            Protein = 11.12m
                        },
                        new
                        {
                            Id = 37,
                            Calories = 218m,
                            Carbs = 39m,
                            CategoryId = 1,
                            Fat = 1m,
                            Name = "كفتة عدس نباتي (Not Fried)",
                            Protein = 15m
                        },
                        new
                        {
                            Id = 38,
                            Calories = 230m,
                            Carbs = 9m,
                            CategoryId = 1,
                            Fat = 17m,
                            Name = "لحمة مفرومة نباتي (Las Vegan)",
                            Protein = 13m
                        },
                        new
                        {
                            Id = 39,
                            Calories = 235m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 11.6m,
                            Name = "جبنة جودا لايت",
                            Protein = 31m
                        },
                        new
                        {
                            Id = 40,
                            Calories = 265m,
                            Carbs = 3.9m,
                            CategoryId = 1,
                            Fat = 21.5m,
                            Name = "جبنة فيتا لايت (المراعي)",
                            Protein = 14.2m
                        },
                        new
                        {
                            Id = 41,
                            Calories = 284m,
                            Carbs = 9m,
                            CategoryId = 1,
                            Fat = 24m,
                            Name = "جبنة مثلثات (بريزيدون)",
                            Protein = 8m
                        },
                        new
                        {
                            Id = 42,
                            Calories = 262m,
                            Carbs = 8m,
                            CategoryId = 1,
                            Fat = 19.8m,
                            Name = "جبنة شرائح برجر (بريزيدون)",
                            Protein = 13m
                        },
                        new
                        {
                            Id = 43,
                            Calories = 308m,
                            Carbs = 6.7m,
                            CategoryId = 1,
                            Fat = 19.1m,
                            Name = "جبنة موزاريلا لايت (بريزيدون)",
                            Protein = 0m
                        },
                        new
                        {
                            Id = 44,
                            Calories = 311m,
                            Carbs = 1.7m,
                            CategoryId = 1,
                            Fat = 23.5m,
                            Name = "جبنة حلومي",
                            Protein = 23.9m
                        },
                        new
                        {
                            Id = 45,
                            Calories = 318m,
                            Carbs = 2.28m,
                            CategoryId = 1,
                            Fat = 24.33m,
                            Name = "جبنة بيضاء عادية",
                            Protein = 22.44m
                        },
                        new
                        {
                            Id = 46,
                            Calories = 318m,
                            Carbs = 2.5m,
                            CategoryId = 1,
                            Fat = 24.6m,
                            Name = "جبنة موزاريلا",
                            Protein = 21.6m
                        },
                        new
                        {
                            Id = 47,
                            Calories = 363.64m,
                            Carbs = 12.12m,
                            CategoryId = 1,
                            Fat = 3.03m,
                            Name = "Egg White Protein",
                            Protein = 69.7m
                        },
                        new
                        {
                            Id = 48,
                            Calories = 377m,
                            Carbs = 11.42m,
                            CategoryId = 1,
                            Fat = 11.4m,
                            Name = "أبوعوف بروتين بار (بندق)",
                            Protein = 37.14m
                        },
                        new
                        {
                            Id = 49,
                            Calories = 387m,
                            Carbs = 3.6m,
                            CategoryId = 1,
                            Fat = 26.9m,
                            Name = "جبنة تركي",
                            Protein = 31.8m
                        },
                        new
                        {
                            Id = 50,
                            Calories = 70m,
                            Carbs = 18.6m,
                            CategoryId = 1,
                            Fat = 0.2m,
                            Name = "جبنة بارميزان",
                            Protein = 0.6m
                        },
                        new
                        {
                            Id = 51,
                            Calories = 53m,
                            Carbs = 3.6m,
                            CategoryId = 1,
                            Fat = 0.1m,
                            Name = "هاي برو (دانون)",
                            Protein = 9.4m
                        },
                        new
                        {
                            Id = 52,
                            Calories = 55m,
                            Carbs = 2.4m,
                            CategoryId = 1,
                            Fat = 0.1m,
                            Name = "بياض بيض",
                            Protein = 10.7m
                        },
                        new
                        {
                            Id = 53,
                            Calories = 58.2m,
                            Carbs = 5m,
                            CategoryId = 1,
                            Fat = 3m,
                            Name = "جهينة لبن رايب (220 مل)",
                            Protein = 2.7m
                        },
                        new
                        {
                            Id = 54,
                            Calories = 120m,
                            Carbs = 3m,
                            CategoryId = 1,
                            Fat = 10m,
                            Name = "واي بروتين (Redcon Isorope)",
                            Protein = 25m
                        },
                        new
                        {
                            Id = 55,
                            Calories = 195m,
                            Carbs = 8.5m,
                            CategoryId = 1,
                            Fat = 13m,
                            Name = "سلطة تونة (ريو ماري)",
                            Protein = 10m
                        },
                        new
                        {
                            Id = 56,
                            Calories = 285m,
                            Carbs = 20m,
                            CategoryId = 1,
                            Fat = 23m,
                            Name = "جبنة موزاريلا نباتي (Violife)",
                            Protein = 0m
                        },
                        new
                        {
                            Id = 57,
                            Calories = 366.7m,
                            Carbs = 0m,
                            CategoryId = 1,
                            Fat = 0m,
                            Name = "كازين",
                            Protein = 86.7m
                        },
                        new
                        {
                            Id = 58,
                            Calories = 373m,
                            Carbs = 6m,
                            CategoryId = 1,
                            Fat = 2.5m,
                            Name = "واي بروتين",
                            Protein = 77.1m
                        },
                        new
                        {
                            Id = 59,
                            Calories = 379m,
                            Carbs = 7.9m,
                            CategoryId = 1,
                            Fat = 3.2m,
                            Name = "أيزو واي (Anabolic)",
                            Protein = 78.9m
                        },
                        new
                        {
                            Id = 60,
                            Calories = 388m,
                            Carbs = 4.5m,
                            CategoryId = 1,
                            Fat = 1m,
                            Name = "واي بروتين (Evolve)",
                            Protein = 88m
                        },
                        new
                        {
                            Id = 61,
                            Calories = 403m,
                            Carbs = 3.4m,
                            CategoryId = 1,
                            Fat = 33.3m,
                            Name = "جبنة شيدر لايت شرائح (بريزيدون)",
                            Protein = 22.9m
                        },
                        new
                        {
                            Id = 62,
                            Calories = 70m,
                            Carbs = 6.2m,
                            CategoryId = 1,
                            Fat = 3.1m,
                            Name = "زبادي كامل الدسم",
                            Protein = 4.4m
                        },
                        new
                        {
                            Id = 63,
                            Calories = 155m,
                            Carbs = 1.1m,
                            CategoryId = 1,
                            Fat = 10.6m,
                            Name = "بيض كامل",
                            Protein = 12.6m
                        },
                        new
                        {
                            Id = 64,
                            Calories = 340m,
                            Carbs = 4.9m,
                            CategoryId = 1,
                            Fat = 5.7m,
                            Name = "بروتين نباتي (ليمتليس)",
                            Protein = 76.7m
                        },
                        new
                        {
                            Id = 65,
                            Calories = 15m,
                            Carbs = 3.63m,
                            CategoryId = 2,
                            Fat = 0.1m,
                            Name = "خيار",
                            Protein = 0.65m
                        },
                        new
                        {
                            Id = 66,
                            Calories = 15m,
                            Carbs = 2.9m,
                            CategoryId = 2,
                            Fat = 0.1m,
                            Name = "خس",
                            Protein = 1.4m
                        },
                        new
                        {
                            Id = 67,
                            Calories = 15m,
                            Carbs = 3.6m,
                            CategoryId = 2,
                            Fat = 0.1m,
                            Name = "خضار أخضر",
                            Protein = 0.6m
                        },
                        new
                        {
                            Id = 68,
                            Calories = 15m,
                            Carbs = 1.3m,
                            CategoryId = 2,
                            Fat = 1m,
                            Name = "لبن لوز",
                            Protein = 0.4m
                        },
                        new
                        {
                            Id = 69,
                            Calories = 17m,
                            Carbs = 3.1m,
                            CategoryId = 2,
                            Fat = 0.3m,
                            Name = "كوسة",
                            Protein = 1.2m
                        },
                        new
                        {
                            Id = 70,
                            Calories = 18m,
                            Carbs = 3.9m,
                            CategoryId = 2,
                            Fat = 0.2m,
                            Name = "طماطم",
                            Protein = 0.9m
                        },
                        new
                        {
                            Id = 71,
                            Calories = 20m,
                            Carbs = 3.9m,
                            CategoryId = 2,
                            Fat = 0.1m,
                            Name = "هليون",
                            Protein = 2.2m
                        },
                        new
                        {
                            Id = 72,
                            Calories = 20m,
                            Carbs = 4.6m,
                            CategoryId = 2,
                            Fat = 0.2m,
                            Name = "فلفل أخضر بارد",
                            Protein = 0.9m
                        },
                        new
                        {
                            Id = 73,
                            Calories = 22m,
                            Carbs = 3.3m,
                            CategoryId = 2,
                            Fat = 0.3m,
                            Name = "مشروم",
                            Protein = 3.1m
                        },
                        new
                        {
                            Id = 74,
                            Calories = 22m,
                            Carbs = 4.5m,
                            CategoryId = 2,
                            Fat = 0.2m,
                            Name = "بامية (بعد الطهي)",
                            Protein = 2m
                        },
                        new
                        {
                            Id = 75,
                            Calories = 23m,
                            Carbs = 3.6m,
                            CategoryId = 2,
                            Fat = 0.4m,
                            Name = "سبانخ",
                            Protein = 2.9m
                        },
                        new
                        {
                            Id = 76,
                            Calories = 25m,
                            Carbs = 6m,
                            CategoryId = 2,
                            Fat = 0.2m,
                            Name = "باذنجان",
                            Protein = 1m
                        },
                        new
                        {
                            Id = 77,
                            Calories = 25m,
                            Carbs = 3.6m,
                            CategoryId = 2,
                            Fat = 0.7m,
                            Name = "جرجير",
                            Protein = 2.6m
                        },
                        new
                        {
                            Id = 78,
                            Calories = 25m,
                            Carbs = 5m,
                            CategoryId = 2,
                            Fat = 0.3m,
                            Name = "قرنبيط",
                            Protein = 1.9m
                        },
                        new
                        {
                            Id = 79,
                            Calories = 26m,
                            Carbs = 6m,
                            CategoryId = 2,
                            Fat = 0.3m,
                            Name = "فلفل أحمر بارد",
                            Protein = 1m
                        },
                        new
                        {
                            Id = 80,
                            Calories = 26.6m,
                            Carbs = 6.6m,
                            CategoryId = 2,
                            Fat = 0m,
                            Name = "صوص لايت (زيرو تريت)",
                            Protein = 0m
                        },
                        new
                        {
                            Id = 81,
                            Calories = 27m,
                            Carbs = 5.7m,
                            CategoryId = 2,
                            Fat = 0.5m,
                            Name = "بصل أخضر",
                            Protein = 1m
                        },
                        new
                        {
                            Id = 82,
                            Calories = 28.7m,
                            Carbs = 5.3m,
                            CategoryId = 2,
                            Fat = 0.3m,
                            Name = "صلصلة طماطم",
                            Protein = 1.2m
                        },
                        new
                        {
                            Id = 83,
                            Calories = 30m,
                            Carbs = 7.6m,
                            CategoryId = 2,
                            Fat = 0.2m,
                            Name = "بطيخ",
                            Protein = 0.6m
                        },
                        new
                        {
                            Id = 84,
                            Calories = 32m,
                            Carbs = 7.7m,
                            CategoryId = 2,
                            Fat = 0.3m,
                            Name = "فراولة",
                            Protein = 0.7m
                        },
                        new
                        {
                            Id = 85,
                            Calories = 34m,
                            Carbs = 6.6m,
                            CategoryId = 2,
                            Fat = 0.4m,
                            Name = "بروكلي",
                            Protein = 2.8m
                        },
                        new
                        {
                            Id = 86,
                            Calories = 34m,
                            Carbs = 8.2m,
                            CategoryId = 2,
                            Fat = 0.2m,
                            Name = "كانتلوب",
                            Protein = 0.8m
                        },
                        new
                        {
                            Id = 87,
                            Calories = 35m,
                            Carbs = 7.9m,
                            CategoryId = 2,
                            Fat = 0.3m,
                            Name = "فاصوليا خضراء",
                            Protein = 1.9m
                        },
                        new
                        {
                            Id = 88,
                            Calories = 39m,
                            Carbs = 9.5m,
                            CategoryId = 2,
                            Fat = 0.3m,
                            Name = "خوخ",
                            Protein = 0.9m
                        },
                        new
                        {
                            Id = 89,
                            Calories = 40m,
                            Carbs = 9.3m,
                            CategoryId = 2,
                            Fat = 0.1m,
                            Name = "بصل",
                            Protein = 1.1m
                        },
                        new
                        {
                            Id = 90,
                            Calories = 41m,
                            Carbs = 10m,
                            CategoryId = 2,
                            Fat = 0.2m,
                            Name = "جزر",
                            Protein = 0.9m
                        },
                        new
                        {
                            Id = 91,
                            Calories = 42m,
                            Carbs = 6.5m,
                            CategoryId = 2,
                            Fat = 0.02m,
                            Name = "ملوخية",
                            Protein = 1.7m
                        },
                        new
                        {
                            Id = 92,
                            Calories = 43m,
                            Carbs = 9.6m,
                            CategoryId = 2,
                            Fat = 0.2m,
                            Name = "بنجر",
                            Protein = 1.6m
                        },
                        new
                        {
                            Id = 93,
                            Calories = 43m,
                            Carbs = 10m,
                            CategoryId = 2,
                            Fat = 0.5m,
                            Name = "توت أسود",
                            Protein = 1.4m
                        },
                        new
                        {
                            Id = 94,
                            Calories = 45m,
                            Carbs = 9.7m,
                            CategoryId = 2,
                            Fat = 0.4m,
                            Name = "عصير برتقال فريش",
                            Protein = 0.8m
                        },
                        new
                        {
                            Id = 95,
                            Calories = 46m,
                            Carbs = 10.7m,
                            CategoryId = 2,
                            Fat = 0.1m,
                            Name = "عصير تفاح فريش",
                            Protein = 0.1m
                        },
                        new
                        {
                            Id = 96,
                            Calories = 47m,
                            Carbs = 12m,
                            CategoryId = 2,
                            Fat = 0.1m,
                            Name = "برتقال",
                            Protein = 0.9m
                        },
                        new
                        {
                            Id = 97,
                            Calories = 47m,
                            Carbs = 12m,
                            CategoryId = 2,
                            Fat = 0.1m,
                            Name = "يوسفي",
                            Protein = 0.9m
                        },
                        new
                        {
                            Id = 98,
                            Calories = 50m,
                            Carbs = 13.1m,
                            CategoryId = 2,
                            Fat = 0.1m,
                            Name = "أناناس",
                            Protein = 0.5m
                        },
                        new
                        {
                            Id = 99,
                            Calories = 50m,
                            Carbs = 12m,
                            CategoryId = 2,
                            Fat = 0.3m,
                            Name = "كرز (أصفر)",
                            Protein = 1m
                        },
                        new
                        {
                            Id = 100,
                            Calories = 52m,
                            Carbs = 14m,
                            CategoryId = 2,
                            Fat = 0.2m,
                            Name = "تفاح",
                            Protein = 0.3m
                        },
                        new
                        {
                            Id = 101,
                            Calories = 52m,
                            Carbs = 11m,
                            CategoryId = 2,
                            Fat = 0.72m,
                            Name = "حرنكش",
                            Protein = 2m
                        },
                        new
                        {
                            Id = 102,
                            Calories = 55m,
                            Carbs = 5.5m,
                            CategoryId = 2,
                            Fat = 2.1m,
                            Name = "لبن نص دسم",
                            Protein = 3.4m
                        },
                        new
                        {
                            Id = 103,
                            Calories = 57m,
                            Carbs = 14.5m,
                            CategoryId = 2,
                            Fat = 0.3m,
                            Name = "توت أزرق",
                            Protein = 0.7m
                        },
                        new
                        {
                            Id = 104,
                            Calories = 57m,
                            Carbs = 15.2m,
                            CategoryId = 2,
                            Fat = 0.1m,
                            Name = "كمثري",
                            Protein = 0.4m
                        },
                        new
                        {
                            Id = 105,
                            Calories = 61m,
                            Carbs = 14.7m,
                            CategoryId = 2,
                            Fat = 0.5m,
                            Name = "كيوي",
                            Protein = 1.1m
                        },
                        new
                        {
                            Id = 106,
                            Calories = 65m,
                            Carbs = 17m,
                            CategoryId = 2,
                            Fat = 0.3m,
                            Name = "مانجو",
                            Protein = 0.5m
                        },
                        new
                        {
                            Id = 107,
                            Calories = 68m,
                            Carbs = 14.3m,
                            CategoryId = 2,
                            Fat = 0m,
                            Name = "جوافة",
                            Protein = 2.5m
                        },
                        new
                        {
                            Id = 108,
                            Calories = 69m,
                            Carbs = 18.1m,
                            CategoryId = 2,
                            Fat = 0.2m,
                            Name = "عنب",
                            Protein = 0.7m
                        },
                        new
                        {
                            Id = 109,
                            Calories = 77m,
                            Carbs = 15.4m,
                            CategoryId = 2,
                            Fat = 0.1m,
                            Name = "بطاطس (بعد الطهي)",
                            Protein = 2.1m
                        },
                        new
                        {
                            Id = 110,
                            Calories = 78m,
                            Carbs = 13m,
                            CategoryId = 2,
                            Fat = 0.77m,
                            Name = "ذرة حلوة (حدائق كاليفورنيا)",
                            Protein = 3m
                        },
                        new
                        {
                            Id = 111,
                            Calories = 83m,
                            Carbs = 15.55m,
                            CategoryId = 2,
                            Fat = 0.22m,
                            Name = "بسلة (بعد الطهي)",
                            Protein = 5.33m
                        },
                        new
                        {
                            Id = 112,
                            Calories = 83m,
                            Carbs = 18.7m,
                            CategoryId = 2,
                            Fat = 0.2m,
                            Name = "برغل (بعد الطهي)",
                            Protein = 3.1m
                        },
                        new
                        {
                            Id = 113,
                            Calories = 83m,
                            Carbs = 18.7m,
                            CategoryId = 2,
                            Fat = 1.2m,
                            Name = "رمان",
                            Protein = 1.7m
                        },
                        new
                        {
                            Id = 114,
                            Calories = 86m,
                            Carbs = 17.1m,
                            CategoryId = 2,
                            Fat = 0.1m,
                            Name = "بطاطا (فبل الطهي)",
                            Protein = 1.6m
                        },
                        new
                        {
                            Id = 115,
                            Calories = 87m,
                            Carbs = 10m,
                            CategoryId = 2,
                            Fat = 0m,
                            Name = "مربي لايت (زيرو تريت)",
                            Protein = 11.5m
                        },
                        new
                        {
                            Id = 116,
                            Calories = 89m,
                            Carbs = 21.3m,
                            CategoryId = 2,
                            Fat = 0.3m,
                            Name = "موز",
                            Protein = 0.7m
                        },
                        new
                        {
                            Id = 117,
                            Calories = 92m,
                            Carbs = 16m,
                            CategoryId = 2,
                            Fat = 0m,
                            Name = "فاصوليا بيضاء",
                            Protein = 6.1m
                        },
                        new
                        {
                            Id = 118,
                            Calories = 94m,
                            Carbs = 13m,
                            CategoryId = 2,
                            Fat = 2.8m,
                            Name = "فول مدمس",
                            Protein = 5.8m
                        },
                        new
                        {
                            Id = 119,
                            Calories = 98m,
                            Carbs = 14m,
                            CategoryId = 2,
                            Fat = 2.4m,
                            Name = "فاصوليا حمراء",
                            Protein = 6m
                        },
                        new
                        {
                            Id = 120,
                            Calories = 100m,
                            Carbs = 22m,
                            CategoryId = 2,
                            Fat = 1.5m,
                            Name = "ذرة",
                            Protein = 3.5m
                        },
                        new
                        {
                            Id = 121,
                            Calories = 106m,
                            Carbs = 12.29m,
                            CategoryId = 2,
                            Fat = 3m,
                            Name = "زبادي يوناني بالفواكه (جهينة)",
                            Protein = 7.33m
                        },
                        new
                        {
                            Id = 122,
                            Calories = 112m,
                            Carbs = 26.46m,
                            CategoryId = 2,
                            Fat = 0.2m,
                            Name = "قلقاس (بعد الطهي)",
                            Protein = 1.5m
                        },
                        new
                        {
                            Id = 123,
                            Calories = 116m,
                            Carbs = 20.8m,
                            CategoryId = 2,
                            Fat = 0.5m,
                            Name = "لوبيا (بعد الطبخ)",
                            Protein = 7.7m
                        },
                        new
                        {
                            Id = 124,
                            Calories = 116.5m,
                            Carbs = 20m,
                            CategoryId = 2,
                            Fat = 0.4m,
                            Name = "فول مدمس مطبوخ",
                            Protein = 8m
                        },
                        new
                        {
                            Id = 125,
                            Calories = 119m,
                            Carbs = 10m,
                            CategoryId = 2,
                            Fat = 2.9m,
                            Name = "ترمس (بعد الطهي)",
                            Protein = 16m
                        },
                        new
                        {
                            Id = 126,
                            Calories = 120m,
                            Carbs = 18.5m,
                            CategoryId = 2,
                            Fat = 1.9m,
                            Name = "كينوا",
                            Protein = 4.4m
                        },
                        new
                        {
                            Id = 127,
                            Calories = 123m,
                            Carbs = 26m,
                            CategoryId = 2,
                            Fat = 0.4m,
                            Name = "أرز (بعد الطهي)",
                            Protein = 2.9m
                        },
                        new
                        {
                            Id = 128,
                            Calories = 124m,
                            Carbs = 26m,
                            CategoryId = 2,
                            Fat = 1m,
                            Name = "أرز بني (بعد الطهي)",
                            Protein = 3m
                        },
                        new
                        {
                            Id = 129,
                            Calories = 131m,
                            Carbs = 25m,
                            CategoryId = 2,
                            Fat = 1.1m,
                            Name = "مكرونة شوفان (بعد الطهي)",
                            Protein = 5m
                        },
                        new
                        {
                            Id = 130,
                            Calories = 140m,
                            Carbs = 23m,
                            CategoryId = 2,
                            Fat = 0.5m,
                            Name = "عدس (بعد الطهي)",
                            Protein = 12m
                        },
                        new
                        {
                            Id = 131,
                            Calories = 149m,
                            Carbs = 26.2m,
                            CategoryId = 2,
                            Fat = 1.7m,
                            Name = "مكرونة (بعد الطهي)",
                            Protein = 6m
                        },
                        new
                        {
                            Id = 132,
                            Calories = 154m,
                            Carbs = 15m,
                            CategoryId = 2,
                            Fat = 1m,
                            Name = "قطع دجاج نباتي (Not Fried)",
                            Protein = 19m
                        },
                        new
                        {
                            Id = 133,
                            Calories = 164m,
                            Carbs = 19.7m,
                            CategoryId = 2,
                            Fat = 2.6m,
                            Name = "حمص ( مسلوق بدون ملح)",
                            Protein = 8.9m
                        },
                        new
                        {
                            Id = 134,
                            Calories = 175m,
                            Carbs = 10m,
                            CategoryId = 2,
                            Fat = 9.1m,
                            Name = "فول صويا (بعد الطهي)",
                            Protein = 16.5m
                        },
                        new
                        {
                            Id = 135,
                            Calories = 175m,
                            Carbs = 29.3m,
                            CategoryId = 2,
                            Fat = 2.7m,
                            Name = "حمص (بعد الطهي)",
                            Protein = 9.8m
                        },
                        new
                        {
                            Id = 136,
                            Calories = 214m,
                            Carbs = 35m,
                            CategoryId = 2,
                            Fat = 2m,
                            Name = "طعمية مصرية (Not Fried)",
                            Protein = 15m
                        },
                        new
                        {
                            Id = 137,
                            Calories = 236.8m,
                            Carbs = 44.1m,
                            CategoryId = 2,
                            Fat = 2.9m,
                            Name = "توست بني",
                            Protein = 8.7m
                        },
                        new
                        {
                            Id = 138,
                            Calories = 247m,
                            Carbs = 65m,
                            CategoryId = 2,
                            Fat = 0.4m,
                            Name = "لبان بدون سكر (ترايدنت)",
                            Protein = 0.5m
                        },
                        new
                        {
                            Id = 139,
                            Calories = 260m,
                            Carbs = 56m,
                            CategoryId = 2,
                            Fat = 0.8m,
                            Name = "عيش بلدي",
                            Protein = 8m
                        },
                        new
                        {
                            Id = 140,
                            Calories = 265m,
                            Carbs = 48.3m,
                            CategoryId = 2,
                            Fat = 3.2m,
                            Name = "عيش أسمر",
                            Protein = 10.7m
                        },
                        new
                        {
                            Id = 141,
                            Calories = 275m,
                            Carbs = 47.5m,
                            CategoryId = 2,
                            Fat = 3.4m,
                            Name = "خبز الشعير",
                            Protein = 9m
                        },
                        new
                        {
                            Id = 142,
                            Calories = 282m,
                            Carbs = 75m,
                            CategoryId = 2,
                            Fat = 0.4m,
                            Name = "بلح (تمر)",
                            Protein = 2.5m
                        },
                        new
                        {
                            Id = 143,
                            Calories = 289m,
                            Carbs = 56m,
                            CategoryId = 2,
                            Fat = 1.8m,
                            Name = "عيش فرنسي (باجيت)",
                            Protein = 12m
                        },
                        new
                        {
                            Id = 144,
                            Calories = 290m,
                            Carbs = 75m,
                            CategoryId = 2,
                            Fat = 0m,
                            Name = "عسل أسود",
                            Protein = 0m
                        },
                        new
                        {
                            Id = 145,
                            Calories = 299m,
                            Carbs = 74.3m,
                            CategoryId = 2,
                            Fat = 0.3m,
                            Name = "زبيب",
                            Protein = 3.3m
                        },
                        new
                        {
                            Id = 146,
                            Calories = 300m,
                            Carbs = 57.5m,
                            CategoryId = 2,
                            Fat = 4m,
                            Name = "عيش (Honey&Dough)",
                            Protein = 10m
                        },
                        new
                        {
                            Id = 147,
                            Calories = 325m,
                            Carbs = 70m,
                            CategoryId = 2,
                            Fat = 2.5m,
                            Name = "فريك",
                            Protein = 15m
                        },
                        new
                        {
                            Id = 148,
                            Calories = 340m,
                            Carbs = 72m,
                            CategoryId = 2,
                            Fat = 2.5m,
                            Name = "دقيق أبيض (كامل الحبة)",
                            Protein = 13.2m
                        },
                        new
                        {
                            Id = 149,
                            Calories = 357m,
                            Carbs = 85.7m,
                            CategoryId = 2,
                            Fat = 0.9m,
                            Name = "رقائق ذرة (كيلوجز)",
                            Protein = 7.1m
                        },
                        new
                        {
                            Id = 150,
                            Calories = 379m,
                            Carbs = 67.7m,
                            CategoryId = 2,
                            Fat = 6.5m,
                            Name = "شوفان (كامل الحبة)",
                            Protein = 13.2m
                        },
                        new
                        {
                            Id = 151,
                            Calories = 379m,
                            Carbs = 67.7m,
                            CategoryId = 2,
                            Fat = 6.5m,
                            Name = "دقيق شوفان (كامل الحبة)",
                            Protein = 13.2m
                        },
                        new
                        {
                            Id = 152,
                            Calories = 383m,
                            Carbs = 75m,
                            CategoryId = 2,
                            Fat = 4m,
                            Name = "رقائق أفطار (نسكويك)",
                            Protein = 7.7m
                        },
                        new
                        {
                            Id = 153,
                            Calories = 387m,
                            Carbs = 81.5m,
                            CategoryId = 2,
                            Fat = 2.8m,
                            Name = "كعك أرز",
                            Protein = 8.2m
                        },
                        new
                        {
                            Id = 154,
                            Calories = 387m,
                            Carbs = 78m,
                            CategoryId = 2,
                            Fat = 4.5m,
                            Name = "فشار (ذرة بعد التحضير)",
                            Protein = 13m
                        },
                        new
                        {
                            Id = 155,
                            Calories = 387m,
                            Carbs = 100m,
                            CategoryId = 2,
                            Fat = 0m,
                            Name = "سكر أبيض",
                            Protein = 0m
                        },
                        new
                        {
                            Id = 156,
                            Calories = 415m,
                            Carbs = 78.5m,
                            CategoryId = 2,
                            Fat = 9.8m,
                            Name = "مقرمشات قرفة",
                            Protein = 6.3m
                        },
                        new
                        {
                            Id = 157,
                            Calories = 450m,
                            Carbs = 44m,
                            CategoryId = 2,
                            Fat = 17m,
                            Name = "جرانولا (ليزي)",
                            Protein = 27m
                        },
                        new
                        {
                            Id = 158,
                            Calories = 460m,
                            Carbs = 61m,
                            CategoryId = 2,
                            Fat = 18m,
                            Name = "جرانولا بالعسل و المكسرات (سانتي)",
                            Protein = 9.8m
                        },
                        new
                        {
                            Id = 159,
                            Calories = 598m,
                            Carbs = 22m,
                            CategoryId = 2,
                            Fat = 51m,
                            Name = "زبدة فول سوداني بالشيكولاتة (أبوعوف)",
                            Protein = 22m
                        },
                        new
                        {
                            Id = 160,
                            Calories = 833m,
                            Carbs = 0m,
                            CategoryId = 2,
                            Fat = 93.3m,
                            Name = "زيت جوز هند",
                            Protein = 0m
                        },
                        new
                        {
                            Id = 161,
                            Calories = 14300m,
                            Carbs = 100m,
                            CategoryId = 2,
                            Fat = 340m,
                            Name = "كريمة الأرز (Bulk)",
                            Protein = 3010m
                        },
                        new
                        {
                            Id = 162,
                            Calories = 1m,
                            Carbs = 0m,
                            CategoryId = 2,
                            Fat = 0m,
                            Name = "قهوة",
                            Protein = 0.1m
                        },
                        new
                        {
                            Id = 163,
                            Calories = 69.8m,
                            Carbs = 15.4m,
                            CategoryId = 2,
                            Fat = 0.1m,
                            Name = "كريمة الأرز",
                            Protein = 1.2m
                        },
                        new
                        {
                            Id = 164,
                            Calories = 195m,
                            Carbs = 45.6m,
                            CategoryId = 2,
                            Fat = 7.6m,
                            Name = "عيش شوفان (ريف)",
                            Protein = 10.5m
                        },
                        new
                        {
                            Id = 165,
                            Calories = 245m,
                            Carbs = 30m,
                            CategoryId = 2,
                            Fat = 1.3m,
                            Name = "عيش شعير (ريف)",
                            Protein = 11.3m
                        },
                        new
                        {
                            Id = 166,
                            Calories = 247m,
                            Carbs = 27.6m,
                            CategoryId = 2,
                            Fat = 1.2m,
                            Name = "قرفة بودره",
                            Protein = 4m
                        },
                        new
                        {
                            Id = 167,
                            Calories = 266m,
                            Carbs = 46.7m,
                            CategoryId = 2,
                            Fat = 3.3m,
                            Name = "توست أبيض",
                            Protein = 8.8m
                        },
                        new
                        {
                            Id = 168,
                            Calories = 304m,
                            Carbs = 81.8m,
                            CategoryId = 2,
                            Fat = 0m,
                            Name = "عسل",
                            Protein = 0.3m
                        },
                        new
                        {
                            Id = 169,
                            Calories = 371m,
                            Carbs = 74.6m,
                            CategoryId = 2,
                            Fat = 1.5m,
                            Name = "سريس ماس (Optimum)",
                            Protein = 14.6m
                        },
                        new
                        {
                            Id = 170,
                            Calories = 463m,
                            Carbs = 48m,
                            CategoryId = 2,
                            Fat = 26m,
                            Name = "نيسكافية 2*1",
                            Protein = 5m
                        },
                        new
                        {
                            Id = 171,
                            Calories = 18m,
                            Carbs = 0.4m,
                            CategoryId = 3,
                            Fat = 1.9m,
                            Name = "لبن جوزهند",
                            Protein = 0.2m
                        },
                        new
                        {
                            Id = 172,
                            Calories = 160m,
                            Carbs = 8.5m,
                            CategoryId = 3,
                            Fat = 14.7m,
                            Name = "أفوكادو",
                            Protein = 2m
                        },
                        new
                        {
                            Id = 173,
                            Calories = 219m,
                            Carbs = 0m,
                            CategoryId = 3,
                            Fat = 18.8m,
                            Name = "Pilaros, Green Olives Stuffed with Almonds",
                            Protein = 3.1m
                        },
                        new
                        {
                            Id = 174,
                            Calories = 230m,
                            Carbs = 3m,
                            CategoryId = 3,
                            Fat = 22m,
                            Name = "لبنة كريمي (كيري)",
                            Protein = 5.5m
                        },
                        new
                        {
                            Id = 175,
                            Calories = 265m,
                            Carbs = 3m,
                            CategoryId = 3,
                            Fat = 27m,
                            Name = "كريمة طهي (جهينة)",
                            Protein = 2.5m
                        },
                        new
                        {
                            Id = 176,
                            Calories = 354m,
                            Carbs = 12.5m,
                            CategoryId = 3,
                            Fat = 33.75m,
                            Name = "جوز هند (بودرة)",
                            Protein = 3.75m
                        },
                        new
                        {
                            Id = 177,
                            Calories = 387m,
                            Carbs = 56.3m,
                            CategoryId = 3,
                            Fat = 9m,
                            Name = "كاكاو خام (دريم)",
                            Protein = 20.3m
                        },
                        new
                        {
                            Id = 178,
                            Calories = 400m,
                            Carbs = 16.3m,
                            CategoryId = 3,
                            Fat = 35.3m,
                            Name = "هيلثي سبريد",
                            Protein = 3.3m
                        },
                        new
                        {
                            Id = 179,
                            Calories = 446m,
                            Carbs = 54m,
                            CategoryId = 3,
                            Fat = 19m,
                            Name = "لب أبيض",
                            Protein = 19m
                        },
                        new
                        {
                            Id = 180,
                            Calories = 486m,
                            Carbs = 42.1m,
                            CategoryId = 3,
                            Fat = 30.7m,
                            Name = "بذور الشيا",
                            Protein = 16.5m
                        },
                        new
                        {
                            Id = 181,
                            Calories = 553m,
                            Carbs = 30.2m,
                            CategoryId = 3,
                            Fat = 43.9m,
                            Name = "كاجو",
                            Protein = 18.2m
                        },
                        new
                        {
                            Id = 182,
                            Calories = 562m,
                            Carbs = 28m,
                            CategoryId = 3,
                            Fat = 45m,
                            Name = "فستق",
                            Protein = 20m
                        },
                        new
                        {
                            Id = 183,
                            Calories = 575m,
                            Carbs = 21.7m,
                            CategoryId = 3,
                            Fat = 49.4m,
                            Name = "لوز",
                            Protein = 21.1m
                        },
                        new
                        {
                            Id = 184,
                            Calories = 585m,
                            Carbs = 21.5m,
                            CategoryId = 3,
                            Fat = 49.7m,
                            Name = "سوداني",
                            Protein = 23.7m
                        },
                        new
                        {
                            Id = 185,
                            Calories = 598m,
                            Carbs = 22.5m,
                            CategoryId = 3,
                            Fat = 50m,
                            Name = "زبدة فول سوداني",
                            Protein = 22.5m
                        },
                        new
                        {
                            Id = 186,
                            Calories = 607.6m,
                            Carbs = 35.34m,
                            CategoryId = 3,
                            Fat = 43.4m,
                            Name = "شوكولاتة دارك (70-80% كاكاو)",
                            Protein = 8.06m
                        },
                        new
                        {
                            Id = 187,
                            Calories = 614m,
                            Carbs = 19m,
                            CategoryId = 3,
                            Fat = 56m,
                            Name = "زبدة لوز",
                            Protein = 21m
                        },
                        new
                        {
                            Id = 188,
                            Calories = 650m,
                            Carbs = 14m,
                            CategoryId = 3,
                            Fat = 65m,
                            Name = "عين جمل",
                            Protein = 15.5m
                        },
                        new
                        {
                            Id = 189,
                            Calories = 690m,
                            Carbs = 14m,
                            CategoryId = 3,
                            Fat = 72m,
                            Name = "بيكان",
                            Protein = 9m
                        },
                        new
                        {
                            Id = 190,
                            Calories = 717m,
                            Carbs = 0.1m,
                            CategoryId = 3,
                            Fat = 81m,
                            Name = "زبدة",
                            Protein = 0.9m
                        },
                        new
                        {
                            Id = 191,
                            Calories = 850m,
                            Carbs = 0m,
                            CategoryId = 3,
                            Fat = 89.5m,
                            Name = "سمنة بلدي",
                            Protein = 0.4m
                        },
                        new
                        {
                            Id = 192,
                            Calories = 884m,
                            Carbs = 0m,
                            CategoryId = 3,
                            Fat = 100m,
                            Name = "زيت زيتون",
                            Protein = 0m
                        });
                });

            modelBuilder.Entity("CoachHussien.Domain.Entities.FoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Protein"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Carbohydrates"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fats"
                        });
                });

            modelBuilder.Entity("CoachHussien.Domain.Entities.Food", b =>
                {
                    b.HasOne("CoachHussien.Domain.Entities.FoodCategory", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoachHussien.Domain.Entities.FoodCategory", b =>
                {
                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
