using Microsoft.EntityFrameworkCore;
using CoachHussien.Domain.Entities;

namespace CoachHussien.Application.Persistence
{
    public static class ModelBuilderExtensions
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            // 1. Seed Categories
            modelBuilder.Entity<FoodCategory>().HasData(
                new FoodCategory { Id = 1, Name = "Protein" },
                new FoodCategory { Id = 2, Name = "Carbohydrates" },
                new FoodCategory { Id = 3, Name = "Fats" }
            );

            // 2. Seed Foods
            // ملاحظة: قمت بتحويل الأرقام وإضافة حرف 'm' للدلالة على decimal
            modelBuilder.Entity<Food>().HasData(
                // --- Protein Sources (CategoryId = 1) ---
                new Food { Id = 1, CategoryId = 1, Name = "لبن خالي الدسم (لامار)", Calories = 35m, Protein = 3.3m, Carbs = 5.2m, Fat = 0.1m },
                new Food { Id = 2, CategoryId = 1, Name = "لبن صويا", Calories = 42m, Protein = 2.5m, Carbs = 3.8m, Fat = 1.5m },
                new Food { Id = 3, CategoryId = 1, Name = "زبادي يوناني ساده (جهينة)", Calories = 50m, Protein = 8.33m, Carbs = 3.61m, Fat = 0.2m },
                new Food { Id = 4, CategoryId = 1, Name = "زبادي لايت (جهينة)", Calories = 51m, Protein = 3.4m, Carbs = 5m, Fat = 1.5m },
                new Food { Id = 5, CategoryId = 1, Name = "لبن خالي من اللاكتوز (جهينة)", Calories = 57m, Protein = 3m, Carbs = 4.5m, Fat = 3m },
                new Food { Id = 6, CategoryId = 1, Name = "لبن كامل الدسم", Calories = 63m, Protein = 3.2m, Carbs = 5m, Fat = 3.4m },
                new Food { Id = 7, CategoryId = 1, Name = "توفو", Calories = 82m, Protein = 3.6m, Carbs = 2.9m, Fat = 9.2m },
                new Food { Id = 8, CategoryId = 1, Name = "جبنة قريش", Calories = 91m, Protein = 12m, Carbs = 2.8m, Fat = 3.5m },
                new Food { Id = 9, CategoryId = 1, Name = "جمبري", Calories = 99m, Protein = 24m, Carbs = 0.2m, Fat = 0.3m },
                new Food { Id = 10, CategoryId = 1, Name = "شرائح دجاج (أطياب)", Calories = 100m, Protein = 15m, Carbs = 10m, Fat = 10m },
                new Food { Id = 11, CategoryId = 1, Name = "بسطرمة", Calories = 102.7m, Protein = 2.8m, Carbs = 0.3m, Fat = 19m },
                new Food { Id = 12, CategoryId = 1, Name = "تونة لايت (صن شاين)", Calories = 103m, Protein = 23m, Carbs = 1m, Fat = 0m },
                new Food { Id = 13, CategoryId = 1, Name = "بييكون (مخلي من الدهون)", Calories = 106m, Protein = 18m, Carbs = 6m, Fat = 0m },
                new Food { Id = 14, CategoryId = 1, Name = "تونة لايت (فيشر مان)", Calories = 116m, Protein = 25.5m, Carbs = 0m, Fat = 0.8m },
                new Food { Id = 15, CategoryId = 1, Name = "سمك هامور (بعد الطهي)", Calories = 118m, Protein = 24.8m, Carbs = 0m, Fat = 1.3m },
                new Food { Id = 16, CategoryId = 1, Name = "سمك قاروص (بعد الطهي)", Calories = 124m, Protein = 23.6m, Carbs = 0m, Fat = 2.6m },
                new Food { Id = 17, CategoryId = 1, Name = "سمك بلطي (بعد الطهي)", Calories = 128m, Protein = 26.2m, Carbs = 0m, Fat = 2.6m },
                new Food { Id = 18, CategoryId = 1, Name = "جبنة فيتا لايت (بريزيدون)", Calories = 131m, Protein = 12m, Carbs = 5m, Fat = 7m },
                new Food { Id = 19, CategoryId = 1, Name = "سمك دنيس (بعد الطهي)", Calories = 135m, Protein = 24.2m, Carbs = 0m, Fat = 3.5m },
                new Food { Id = 20, CategoryId = 1, Name = "قطع سيتان نباتي (Not Fried)", Calories = 138m, Protein = 19m, Carbs = 14m, Fat = 1m },
                new Food { Id = 21, CategoryId = 1, Name = "جبنة لايت اسبريد (بريزيدون)", Calories = 140m, Protein = 12m, Carbs = 5m, Fat = 8m },
                new Food { Id = 22, CategoryId = 1, Name = "سلطة تونة مكسيكية (فيشر مان)", Calories = 141m, Protein = 11.4m, Carbs = 6.8m, Fat = 6.7m },
                new Food { Id = 23, CategoryId = 1, Name = "سلمون", Calories = 149m, Protein = 25.6m, Carbs = 0m, Fat = 4.4m },
                new Food { Id = 24, CategoryId = 1, Name = "شرائح دجاج نباتي (Not Fried)", Calories = 149m, Protein = 20m, Carbs = 13m, Fat = 1m },
                new Food { Id = 25, CategoryId = 1, Name = "سمك بوري (بعد الطهي)", Calories = 150m, Protein = 24.8m, Carbs = 0m, Fat = 4.9m },
                new Food { Id = 26, CategoryId = 1, Name = "لحمة مفرومة (متشفية من غير دهون)", Calories = 153m, Protein = 26.4m, Carbs = 0m, Fat = 4.5m },
                new Food { Id = 27, CategoryId = 1, Name = "جبنة فلاديفيا لايت", Calories = 153m, Protein = 6m, Carbs = 4.3m, Fat = 12m },
                new Food { Id = 28, CategoryId = 1, Name = "ستيك لحمة", Calories = 160m, Protein = 29.9m, Carbs = 0m, Fat = 4.5m },
                new Food { Id = 29, CategoryId = 1, Name = "صدور دجاج (بعد الطهي)", Calories = 165m, Protein = 31m, Carbs = 0m, Fat = 3.6m },
                new Food { Id = 30, CategoryId = 1, Name = "كبدة دجاج (بعد الطهي)", Calories = 167m, Protein = 24.5m, Carbs = 0.7m, Fat = 6.5m },
                new Food { Id = 31, CategoryId = 1, Name = "فصوص تركي", Calories = 170m, Protein = 29.29m, Carbs = 2m, Fat = 5m },
                new Food { Id = 32, CategoryId = 1, Name = "روست بيف", Calories = 170m, Protein = 29m, Carbs = 0m, Fat = 6m },
                new Food { Id = 33, CategoryId = 1, Name = "مكعبات لحمة حمراء (بعد الطهي)", Calories = 187m, Protein = 29.81m, Carbs = 0m, Fat = 6.63m },
                new Food { Id = 34, CategoryId = 1, Name = "كبدة بقري (بعد الطهي)", Calories = 191m, Protein = 29.1m, Carbs = 5.1m, Fat = 5.3m },
                new Food { Id = 35, CategoryId = 1, Name = "سردين", Calories = 195m, Protein = 25.3m, Carbs = 0m, Fat = 10.4m },
                new Food { Id = 36, CategoryId = 1, Name = "كرات لحم نباتي (Las Vegan)", Calories = 211m, Protein = 11.12m, Carbs = 14.68m, Fat = 13.26m },
                new Food { Id = 37, CategoryId = 1, Name = "كفتة عدس نباتي (Not Fried)", Calories = 218m, Protein = 15m, Carbs = 39m, Fat = 1m },
                new Food { Id = 38, CategoryId = 1, Name = "لحمة مفرومة نباتي (Las Vegan)", Calories = 230m, Protein = 13m, Carbs = 9m, Fat = 17m },
                new Food { Id = 39, CategoryId = 1, Name = "جبنة جودا لايت", Calories = 235m, Protein = 31m, Carbs = 0m, Fat = 11.6m },
                new Food { Id = 40, CategoryId = 1, Name = "جبنة فيتا لايت (المراعي)", Calories = 265m, Protein = 14.2m, Carbs = 3.9m, Fat = 21.5m },
                new Food { Id = 41, CategoryId = 1, Name = "جبنة مثلثات (بريزيدون)", Calories = 284m, Protein = 8m, Carbs = 9m, Fat = 24m },
                new Food { Id = 42, CategoryId = 1, Name = "جبنة شرائح برجر (بريزيدون)", Calories = 262m, Protein = 13m, Carbs = 8m, Fat = 19.8m },
                new Food { Id = 43, CategoryId = 1, Name = "جبنة موزاريلا لايت (بريزيدون)", Calories = 308m, Protein = 0m, Carbs = 6.7m, Fat = 19.1m },
                new Food { Id = 44, CategoryId = 1, Name = "جبنة حلومي", Calories = 311m, Protein = 23.9m, Carbs = 1.7m, Fat = 23.5m },
                new Food { Id = 45, CategoryId = 1, Name = "جبنة بيضاء عادية", Calories = 318m, Protein = 22.44m, Carbs = 2.28m, Fat = 24.33m },
                new Food { Id = 46, CategoryId = 1, Name = "جبنة موزاريلا", Calories = 318m, Protein = 21.6m, Carbs = 2.5m, Fat = 24.6m },
                new Food { Id = 47, CategoryId = 1, Name = "Egg White Protein", Calories = 363.64m, Protein = 69.7m, Carbs = 12.12m, Fat = 3.03m },
                new Food { Id = 48, CategoryId = 1, Name = "أبوعوف بروتين بار (بندق)", Calories = 377m, Protein = 37.14m, Carbs = 11.42m, Fat = 11.4m },
                new Food { Id = 49, CategoryId = 1, Name = "جبنة تركي", Calories = 387m, Protein = 31.8m, Carbs = 3.6m, Fat = 26.9m },
                new Food { Id = 50, CategoryId = 1, Name = "جبنة بارميزان", Calories = 70m, Protein = 0.6m, Carbs = 18.6m, Fat = 0.2m },
                new Food { Id = 51, CategoryId = 1, Name = "هاي برو (دانون)", Calories = 53m, Protein = 9.4m, Carbs = 3.6m, Fat = 0.1m },
                new Food { Id = 52, CategoryId = 1, Name = "بياض بيض", Calories = 55m, Protein = 10.7m, Carbs = 2.4m, Fat = 0.1m },
                new Food { Id = 53, CategoryId = 1, Name = "جهينة لبن رايب (220 مل)", Calories = 58.2m, Protein = 2.7m, Carbs = 5m, Fat = 3m },
                new Food { Id = 54, CategoryId = 1, Name = "واي بروتين (Redcon Isorope)", Calories = 120m, Protein = 25m, Carbs = 3m, Fat = 10m },
                new Food { Id = 55, CategoryId = 1, Name = "سلطة تونة (ريو ماري)", Calories = 195m, Protein = 10m, Carbs = 8.5m, Fat = 13m },
                new Food { Id = 56, CategoryId = 1, Name = "جبنة موزاريلا نباتي (Violife)", Calories = 285m, Protein = 0m, Carbs = 20m, Fat = 23m },
                new Food { Id = 57, CategoryId = 1, Name = "كازين", Calories = 366.7m, Protein = 86.7m, Carbs = 0m, Fat = 0m },
                new Food { Id = 58, CategoryId = 1, Name = "واي بروتين", Calories = 373m, Protein = 77.1m, Carbs = 6m, Fat = 2.5m },
                new Food { Id = 59, CategoryId = 1, Name = "أيزو واي (Anabolic)", Calories = 379m, Protein = 78.9m, Carbs = 7.9m, Fat = 3.2m },
                new Food { Id = 60, CategoryId = 1, Name = "واي بروتين (Evolve)", Calories = 388m, Protein = 88m, Carbs = 4.5m, Fat = 1m },
                new Food { Id = 61, CategoryId = 1, Name = "جبنة شيدر لايت شرائح (بريزيدون)", Calories = 403m, Protein = 22.9m, Carbs = 3.4m, Fat = 33.3m },
                new Food { Id = 62, CategoryId = 1, Name = "زبادي كامل الدسم", Calories = 70m, Protein = 4.4m, Carbs = 6.2m, Fat = 3.1m },
                new Food { Id = 63, CategoryId = 1, Name = "بيض كامل", Calories = 155m, Protein = 12.6m, Carbs = 1.1m, Fat = 10.6m },
                new Food { Id = 64, CategoryId = 1, Name = "بروتين نباتي (ليمتليس)", Calories = 340m, Protein = 76.7m, Carbs = 4.9m, Fat = 5.7m },

                // --- Carbohydrates Sources (CategoryId = 2) ---
                new Food { Id = 65, CategoryId = 2, Name = "خيار", Calories = 15m, Protein = 0.65m, Carbs = 3.63m, Fat = 0.1m },
                new Food { Id = 66, CategoryId = 2, Name = "خس", Calories = 15m, Protein = 1.4m, Carbs = 2.9m, Fat = 0.1m },
                new Food { Id = 67, CategoryId = 2, Name = "خضار أخضر", Calories = 15m, Protein = 0.6m, Carbs = 3.6m, Fat = 0.1m },
                new Food { Id = 68, CategoryId = 2, Name = "لبن لوز", Calories = 15m, Protein = 0.4m, Carbs = 1.3m, Fat = 1m },
                new Food { Id = 69, CategoryId = 2, Name = "كوسة", Calories = 17m, Protein = 1.2m, Carbs = 3.1m, Fat = 0.3m },
                new Food { Id = 70, CategoryId = 2, Name = "طماطم", Calories = 18m, Protein = 0.9m, Carbs = 3.9m, Fat = 0.2m },
                new Food { Id = 71, CategoryId = 2, Name = "هليون", Calories = 20m, Protein = 2.2m, Carbs = 3.9m, Fat = 0.1m },
                new Food { Id = 72, CategoryId = 2, Name = "فلفل أخضر بارد", Calories = 20m, Protein = 0.9m, Carbs = 4.6m, Fat = 0.2m },
                new Food { Id = 73, CategoryId = 2, Name = "مشروم", Calories = 22m, Protein = 3.1m, Carbs = 3.3m, Fat = 0.3m },
                new Food { Id = 74, CategoryId = 2, Name = "بامية (بعد الطهي)", Calories = 22m, Protein = 2m, Carbs = 4.5m, Fat = 0.2m },
                new Food { Id = 75, CategoryId = 2, Name = "سبانخ", Calories = 23m, Protein = 2.9m, Carbs = 3.6m, Fat = 0.4m },
                new Food { Id = 76, CategoryId = 2, Name = "باذنجان", Calories = 25m, Protein = 1m, Carbs = 6m, Fat = 0.2m },
                new Food { Id = 77, CategoryId = 2, Name = "جرجير", Calories = 25m, Protein = 2.6m, Carbs = 3.6m, Fat = 0.7m },
                new Food { Id = 78, CategoryId = 2, Name = "قرنبيط", Calories = 25m, Protein = 1.9m, Carbs = 5m, Fat = 0.3m },
                new Food { Id = 79, CategoryId = 2, Name = "فلفل أحمر بارد", Calories = 26m, Protein = 1m, Carbs = 6m, Fat = 0.3m },
                new Food { Id = 80, CategoryId = 2, Name = "صوص لايت (زيرو تريت)", Calories = 26.6m, Protein = 0m, Carbs = 6.6m, Fat = 0m },
                new Food { Id = 81, CategoryId = 2, Name = "بصل أخضر", Calories = 27m, Protein = 1m, Carbs = 5.7m, Fat = 0.5m },
                new Food { Id = 82, CategoryId = 2, Name = "صلصلة طماطم", Calories = 28.7m, Protein = 1.2m, Carbs = 5.3m, Fat = 0.3m },
                new Food { Id = 83, CategoryId = 2, Name = "بطيخ", Calories = 30m, Protein = 0.6m, Carbs = 7.6m, Fat = 0.2m },
                new Food { Id = 84, CategoryId = 2, Name = "فراولة", Calories = 32m, Protein = 0.7m, Carbs = 7.7m, Fat = 0.3m },
                new Food { Id = 85, CategoryId = 2, Name = "بروكلي", Calories = 34m, Protein = 2.8m, Carbs = 6.6m, Fat = 0.4m },
                new Food { Id = 86, CategoryId = 2, Name = "كانتلوب", Calories = 34m, Protein = 0.8m, Carbs = 8.2m, Fat = 0.2m },
                new Food { Id = 87, CategoryId = 2, Name = "فاصوليا خضراء", Calories = 35m, Protein = 1.9m, Carbs = 7.9m, Fat = 0.3m },
                new Food { Id = 88, CategoryId = 2, Name = "خوخ", Calories = 39m, Protein = 0.9m, Carbs = 9.5m, Fat = 0.3m },
                new Food { Id = 89, CategoryId = 2, Name = "بصل", Calories = 40m, Protein = 1.1m, Carbs = 9.3m, Fat = 0.1m },
                new Food { Id = 90, CategoryId = 2, Name = "جزر", Calories = 41m, Protein = 0.9m, Carbs = 10m, Fat = 0.2m },
                new Food { Id = 91, CategoryId = 2, Name = "ملوخية", Calories = 42m, Protein = 1.7m, Carbs = 6.5m, Fat = 0.02m },
                new Food { Id = 92, CategoryId = 2, Name = "بنجر", Calories = 43m, Protein = 1.6m, Carbs = 9.6m, Fat = 0.2m },
                new Food { Id = 93, CategoryId = 2, Name = "توت أسود", Calories = 43m, Protein = 1.4m, Carbs = 10m, Fat = 0.5m },
                new Food { Id = 94, CategoryId = 2, Name = "عصير برتقال فريش", Calories = 45m, Protein = 0.8m, Carbs = 9.7m, Fat = 0.4m },
                new Food { Id = 95, CategoryId = 2, Name = "عصير تفاح فريش", Calories = 46m, Protein = 0.1m, Carbs = 10.7m, Fat = 0.1m },
                new Food { Id = 96, CategoryId = 2, Name = "برتقال", Calories = 47m, Protein = 0.9m, Carbs = 12m, Fat = 0.1m },
                new Food { Id = 97, CategoryId = 2, Name = "يوسفي", Calories = 47m, Protein = 0.9m, Carbs = 12m, Fat = 0.1m },
                new Food { Id = 98, CategoryId = 2, Name = "أناناس", Calories = 50m, Protein = 0.5m, Carbs = 13.1m, Fat = 0.1m },
                new Food { Id = 99, CategoryId = 2, Name = "كرز (أصفر)", Calories = 50m, Protein = 1m, Carbs = 12m, Fat = 0.3m },
                new Food { Id = 100, CategoryId = 2, Name = "تفاح", Calories = 52m, Protein = 0.3m, Carbs = 14m, Fat = 0.2m },
                new Food { Id = 101, CategoryId = 2, Name = "حرنكش", Calories = 52m, Protein = 2m, Carbs = 11m, Fat = 0.72m },
                new Food { Id = 102, CategoryId = 2, Name = "لبن نص دسم", Calories = 55m, Protein = 3.4m, Carbs = 5.5m, Fat = 2.1m },
                new Food { Id = 103, CategoryId = 2, Name = "توت أزرق", Calories = 57m, Protein = 0.7m, Carbs = 14.5m, Fat = 0.3m },
                new Food { Id = 104, CategoryId = 2, Name = "كمثري", Calories = 57m, Protein = 0.4m, Carbs = 15.2m, Fat = 0.1m },
                new Food { Id = 105, CategoryId = 2, Name = "كيوي", Calories = 61m, Protein = 1.1m, Carbs = 14.7m, Fat = 0.5m },
                new Food { Id = 106, CategoryId = 2, Name = "مانجو", Calories = 65m, Protein = 0.5m, Carbs = 17m, Fat = 0.3m },
                new Food { Id = 107, CategoryId = 2, Name = "جوافة", Calories = 68m, Protein = 2.5m, Carbs = 14.3m, Fat = 0m },
                new Food { Id = 108, CategoryId = 2, Name = "عنب", Calories = 69m, Protein = 0.7m, Carbs = 18.1m, Fat = 0.2m },
                new Food { Id = 109, CategoryId = 2, Name = "بطاطس (بعد الطهي)", Calories = 77m, Protein = 2.1m, Carbs = 15.4m, Fat = 0.1m },
                new Food { Id = 110, CategoryId = 2, Name = "ذرة حلوة (حدائق كاليفورنيا)", Calories = 78m, Protein = 3m, Carbs = 13m, Fat = 0.77m },
                new Food { Id = 111, CategoryId = 2, Name = "بسلة (بعد الطهي)", Calories = 83m, Protein = 5.33m, Carbs = 15.55m, Fat = 0.22m },
                new Food { Id = 112, CategoryId = 2, Name = "برغل (بعد الطهي)", Calories = 83m, Protein = 3.1m, Carbs = 18.7m, Fat = 0.2m },
                new Food { Id = 113, CategoryId = 2, Name = "رمان", Calories = 83m, Protein = 1.7m, Carbs = 18.7m, Fat = 1.2m },
                new Food { Id = 114, CategoryId = 2, Name = "بطاطا (فبل الطهي)", Calories = 86m, Protein = 1.6m, Carbs = 17.1m, Fat = 0.1m },
                new Food { Id = 115, CategoryId = 2, Name = "مربي لايت (زيرو تريت)", Calories = 87m, Protein = 11.5m, Carbs = 10m, Fat = 0m },
                new Food { Id = 116, CategoryId = 2, Name = "موز", Calories = 89m, Protein = 0.7m, Carbs = 21.3m, Fat = 0.3m },
                new Food { Id = 117, CategoryId = 2, Name = "فاصوليا بيضاء", Calories = 92m, Protein = 6.1m, Carbs = 16m, Fat = 0m },
                new Food { Id = 118, CategoryId = 2, Name = "فول مدمس", Calories = 94m, Protein = 5.8m, Carbs = 13m, Fat = 2.8m },
                new Food { Id = 119, CategoryId = 2, Name = "فاصوليا حمراء", Calories = 98m, Protein = 6m, Carbs = 14m, Fat = 2.4m },
                new Food { Id = 120, CategoryId = 2, Name = "ذرة", Calories = 100m, Protein = 3.5m, Carbs = 22m, Fat = 1.5m },
                new Food { Id = 121, CategoryId = 2, Name = "زبادي يوناني بالفواكه (جهينة)", Calories = 106m, Protein = 7.33m, Carbs = 12.29m, Fat = 3m },
                new Food { Id = 122, CategoryId = 2, Name = "قلقاس (بعد الطهي)", Calories = 112m, Protein = 1.5m, Carbs = 26.46m, Fat = 0.2m },
                new Food { Id = 123, CategoryId = 2, Name = "لوبيا (بعد الطبخ)", Calories = 116m, Protein = 7.7m, Carbs = 20.8m, Fat = 0.5m },
                new Food { Id = 124, CategoryId = 2, Name = "فول مدمس مطبوخ", Calories = 116.5m, Protein = 8m, Carbs = 20m, Fat = 0.4m },
                new Food { Id = 125, CategoryId = 2, Name = "ترمس (بعد الطهي)", Calories = 119m, Protein = 16m, Carbs = 10m, Fat = 2.9m },
                new Food { Id = 126, CategoryId = 2, Name = "كينوا", Calories = 120m, Protein = 4.4m, Carbs = 18.5m, Fat = 1.9m },
                new Food { Id = 127, CategoryId = 2, Name = "أرز (بعد الطهي)", Calories = 123m, Protein = 2.9m, Carbs = 26m, Fat = 0.4m },
                new Food { Id = 128, CategoryId = 2, Name = "أرز بني (بعد الطهي)", Calories = 124m, Protein = 3m, Carbs = 26m, Fat = 1m },
                new Food { Id = 129, CategoryId = 2, Name = "مكرونة شوفان (بعد الطهي)", Calories = 131m, Protein = 5m, Carbs = 25m, Fat = 1.1m },
                new Food { Id = 130, CategoryId = 2, Name = "عدس (بعد الطهي)", Calories = 140m, Protein = 12m, Carbs = 23m, Fat = 0.5m },
                new Food { Id = 131, CategoryId = 2, Name = "مكرونة (بعد الطهي)", Calories = 149m, Protein = 6m, Carbs = 26.2m, Fat = 1.7m },
                new Food { Id = 132, CategoryId = 2, Name = "قطع دجاج نباتي (Not Fried)", Calories = 154m, Protein = 19m, Carbs = 15m, Fat = 1m },
                new Food { Id = 133, CategoryId = 2, Name = "حمص ( مسلوق بدون ملح)", Calories = 164m, Protein = 8.9m, Carbs = 19.7m, Fat = 2.6m },
                new Food { Id = 134, CategoryId = 2, Name = "فول صويا (بعد الطهي)", Calories = 175m, Protein = 16.5m, Carbs = 10m, Fat = 9.1m },
                new Food { Id = 135, CategoryId = 2, Name = "حمص (بعد الطهي)", Calories = 175m, Protein = 9.8m, Carbs = 29.3m, Fat = 2.7m },
                new Food { Id = 136, CategoryId = 2, Name = "طعمية مصرية (Not Fried)", Calories = 214m, Protein = 15m, Carbs = 35m, Fat = 2m },
                new Food { Id = 137, CategoryId = 2, Name = "توست بني", Calories = 236.8m, Protein = 8.7m, Carbs = 44.1m, Fat = 2.9m },
                new Food { Id = 138, CategoryId = 2, Name = "لبان بدون سكر (ترايدنت)", Calories = 247m, Protein = 0.5m, Carbs = 65m, Fat = 0.4m },
                new Food { Id = 139, CategoryId = 2, Name = "عيش بلدي", Calories = 260m, Protein = 8m, Carbs = 56m, Fat = 0.8m },
                new Food { Id = 140, CategoryId = 2, Name = "عيش أسمر", Calories = 265m, Protein = 10.7m, Carbs = 48.3m, Fat = 3.2m },
                new Food { Id = 141, CategoryId = 2, Name = "خبز الشعير", Calories = 275m, Protein = 9m, Carbs = 47.5m, Fat = 3.4m },
                new Food { Id = 142, CategoryId = 2, Name = "بلح (تمر)", Calories = 282m, Protein = 2.5m, Carbs = 75m, Fat = 0.4m },
                new Food { Id = 143, CategoryId = 2, Name = "عيش فرنسي (باجيت)", Calories = 289m, Protein = 12m, Carbs = 56m, Fat = 1.8m },
                new Food { Id = 144, CategoryId = 2, Name = "عسل أسود", Calories = 290m, Protein = 0m, Carbs = 75m, Fat = 0m },
                new Food { Id = 145, CategoryId = 2, Name = "زبيب", Calories = 299m, Protein = 3.3m, Carbs = 74.3m, Fat = 0.3m },
                new Food { Id = 146, CategoryId = 2, Name = "عيش (Honey&Dough)", Calories = 300m, Protein = 10m, Carbs = 57.5m, Fat = 4m },
                new Food { Id = 147, CategoryId = 2, Name = "فريك", Calories = 325m, Protein = 15m, Carbs = 70m, Fat = 2.5m },
                new Food { Id = 148, CategoryId = 2, Name = "دقيق أبيض (كامل الحبة)", Calories = 340m, Protein = 13.2m, Carbs = 72m, Fat = 2.5m },
                new Food { Id = 149, CategoryId = 2, Name = "رقائق ذرة (كيلوجز)", Calories = 357m, Protein = 7.1m, Carbs = 85.7m, Fat = 0.9m },
                new Food { Id = 150, CategoryId = 2, Name = "شوفان (كامل الحبة)", Calories = 379m, Protein = 13.2m, Carbs = 67.7m, Fat = 6.5m },
                new Food { Id = 151, CategoryId = 2, Name = "دقيق شوفان (كامل الحبة)", Calories = 379m, Protein = 13.2m, Carbs = 67.7m, Fat = 6.5m },
                new Food { Id = 152, CategoryId = 2, Name = "رقائق أفطار (نسكويك)", Calories = 383m, Protein = 7.7m, Carbs = 75m, Fat = 4m },
                new Food { Id = 153, CategoryId = 2, Name = "كعك أرز", Calories = 387m, Protein = 8.2m, Carbs = 81.5m, Fat = 2.8m },
                new Food { Id = 154, CategoryId = 2, Name = "فشار (ذرة بعد التحضير)", Calories = 387m, Protein = 13m, Carbs = 78m, Fat = 4.5m },
                new Food { Id = 155, CategoryId = 2, Name = "سكر أبيض", Calories = 387m, Protein = 0m, Carbs = 100m, Fat = 0m },
                new Food { Id = 156, CategoryId = 2, Name = "مقرمشات قرفة", Calories = 415m, Protein = 6.3m, Carbs = 78.5m, Fat = 9.8m },
                new Food { Id = 157, CategoryId = 2, Name = "جرانولا (ليزي)", Calories = 450m, Protein = 27m, Carbs = 44m, Fat = 17m },
                new Food { Id = 158, CategoryId = 2, Name = "جرانولا بالعسل و المكسرات (سانتي)", Calories = 460m, Protein = 9.8m, Carbs = 61m, Fat = 18m },
                new Food { Id = 159, CategoryId = 2, Name = "زبدة فول سوداني بالشيكولاتة (أبوعوف)", Calories = 598m, Protein = 22m, Carbs = 22m, Fat = 51m },
                new Food { Id = 160, CategoryId = 2, Name = "زيت جوز هند", Calories = 833m, Protein = 0m, Carbs = 0m, Fat = 93.3m },
                new Food { Id = 161, CategoryId = 2, Name = "كريمة الأرز (Bulk)", Calories = 14300m, Protein = 3010m, Carbs = 100m, Fat = 340m }, // قيمة ضخمة، تأكد منها
                new Food { Id = 162, CategoryId = 2, Name = "قهوة", Calories = 1m, Protein = 0.1m, Carbs = 0m, Fat = 0m },
                new Food { Id = 163, CategoryId = 2, Name = "كريمة الأرز", Calories = 69.8m, Protein = 1.2m, Carbs = 15.4m, Fat = 0.1m },
                new Food { Id = 164, CategoryId = 2, Name = "عيش شوفان (ريف)", Calories = 195m, Protein = 10.5m, Carbs = 45.6m, Fat = 7.6m },
                new Food { Id = 165, CategoryId = 2, Name = "عيش شعير (ريف)", Calories = 245m, Protein = 11.3m, Carbs = 30m, Fat = 1.3m },
                new Food { Id = 166, CategoryId = 2, Name = "قرفة بودره", Calories = 247m, Protein = 4m, Carbs = 27.6m, Fat = 1.2m },
                new Food { Id = 167, CategoryId = 2, Name = "توست أبيض", Calories = 266m, Protein = 8.8m, Carbs = 46.7m, Fat = 3.3m },
                new Food { Id = 168, CategoryId = 2, Name = "عسل", Calories = 304m, Protein = 0.3m, Carbs = 81.8m, Fat = 0m },
                new Food { Id = 169, CategoryId = 2, Name = "سريس ماس (Optimum)", Calories = 371m, Protein = 14.6m, Carbs = 74.6m, Fat = 1.5m },
                new Food { Id = 170, CategoryId = 2, Name = "نيسكافية 2*1", Calories = 463m, Protein = 5m, Carbs = 48m, Fat = 26m },

                // --- Fats Sources (CategoryId = 3) ---
                new Food { Id = 171, CategoryId = 3, Name = "لبن جوزهند", Calories = 18m, Protein = 0.2m, Carbs = 0.4m, Fat = 1.9m },
                new Food { Id = 172, CategoryId = 3, Name = "أفوكادو", Calories = 160m, Protein = 2m, Carbs = 8.5m, Fat = 14.7m },
                new Food { Id = 173, CategoryId = 3, Name = "Pilaros, Green Olives Stuffed with Almonds", Calories = 219m, Protein = 3.1m, Carbs = 0m, Fat = 18.8m },
                new Food { Id = 174, CategoryId = 3, Name = "لبنة كريمي (كيري)", Calories = 230m, Protein = 5.5m, Carbs = 3m, Fat = 22m },
                new Food { Id = 175, CategoryId = 3, Name = "كريمة طهي (جهينة)", Calories = 265m, Protein = 2.5m, Carbs = 3m, Fat = 27m },
                new Food { Id = 176, CategoryId = 3, Name = "جوز هند (بودرة)", Calories = 354m, Protein = 3.75m, Carbs = 12.5m, Fat = 33.75m },
                new Food { Id = 177, CategoryId = 3, Name = "كاكاو خام (دريم)", Calories = 387m, Protein = 20.3m, Carbs = 56.3m, Fat = 9m },
                new Food { Id = 178, CategoryId = 3, Name = "هيلثي سبريد", Calories = 400m, Protein = 3.3m, Carbs = 16.3m, Fat = 35.3m },
                new Food { Id = 179, CategoryId = 3, Name = "لب أبيض", Calories = 446m, Protein = 19m, Carbs = 54m, Fat = 19m },
                new Food { Id = 180, CategoryId = 3, Name = "بذور الشيا", Calories = 486m, Protein = 16.5m, Carbs = 42.1m, Fat = 30.7m },
                new Food { Id = 181, CategoryId = 3, Name = "كاجو", Calories = 553m, Protein = 18.2m, Carbs = 30.2m, Fat = 43.9m },
                new Food { Id = 182, CategoryId = 3, Name = "فستق", Calories = 562m, Protein = 20m, Carbs = 28m, Fat = 45m },
                new Food { Id = 183, CategoryId = 3, Name = "لوز", Calories = 575m, Protein = 21.1m, Carbs = 21.7m, Fat = 49.4m },
                new Food { Id = 184, CategoryId = 3, Name = "سوداني", Calories = 585m, Protein = 23.7m, Carbs = 21.5m, Fat = 49.7m },
                new Food { Id = 185, CategoryId = 3, Name = "زبدة فول سوداني", Calories = 598m, Protein = 22.5m, Carbs = 22.5m, Fat = 50m },
                new Food { Id = 186, CategoryId = 3, Name = "شوكولاتة دارك (70-80% كاكاو)", Calories = 607.6m, Protein = 8.06m, Carbs = 35.34m, Fat = 43.4m },
                new Food { Id = 187, CategoryId = 3, Name = "زبدة لوز", Calories = 614m, Protein = 21m, Carbs = 19m, Fat = 56m },
                new Food { Id = 188, CategoryId = 3, Name = "عين جمل", Calories = 650m, Protein = 15.5m, Carbs = 14m, Fat = 65m },
                new Food { Id = 189, CategoryId = 3, Name = "بيكان", Calories = 690m, Protein = 9m, Carbs = 14m, Fat = 72m }, // لاحظت تكرار البيكان في الداتا وحذفت واحد
                new Food { Id = 190, CategoryId = 3, Name = "زبدة", Calories = 717m, Protein = 0.9m, Carbs = 0.1m, Fat = 81m },
                new Food { Id = 191, CategoryId = 3, Name = "سمنة بلدي", Calories = 850m, Protein = 0.4m, Carbs = 0m, Fat = 89.5m },
                new Food { Id = 192, CategoryId = 3, Name = "زيت زيتون", Calories = 884m, Protein = 0m, Carbs = 0m, Fat = 100m }
            );
        }
    }
}
